git-cms-addpkg

When -f <input> file is provided then git-cms-addpkg always exit with exit code 1
- first we should check for $HEADER only after looping over all packages
- need to explicitly exit with 0 at the end otherwise script exit with exit code of last command which in case of every think OK is   [ "$HEADER" ]

exit with zero code if input file is provided and all packages are properly checked out

---

git-cms-sparse-checkout

current version kills possibility to merge-topic changes with non-package structure.
A specific example is when using submodules .gitmodules file and the submodule reference do not make it properly to the local copy.
the sed preselection will add the trailing slash for CMSSW packages (all have a form of sub/pack),
but not for other elements (files or submodule references and such)

add trailing slash only if one is already available for sparse-checkout 

---

git-cms-addpkg
git-cms-init
git-cms-merge-topic
git-cms-sparse-checkout

reimplenent the verbose and debug messages without referencing /dev/stdout or
/dev/stderr, which may be unavailable (e.g. running inside a container)

reimplement logging without referencing file descriptors

---

docs/man/git-cms-checkout-topic.1.in
git-cms-checkout-topic
git-cms-merge-topic

This adds `cms-checkout-topic` as a wrapper for a new `--no-merge` option in `cms-merge-topic`. This option is primarily intended to help with rebasing PRs, by allowing users to set up the modified packages and source code for a topic branch in a release area *without* doing a merge (which can cause 100s of duplicate commits).
Most of the functionality is duplicated from `cms-merge-topic`, so the new option is added there rather than making an entirely separate script. The `cms-checkout-topic` wrapper is added to have a more self-explanatory description of the command (however git-esque `cms-merge-topic --no-merge` might be...).

Add cms-checkout-topic tool

---

docs/man/git-cms-addpkg.1.in
docs/man/git-cms-rmpkg.1.in
git-cms-addpkg
git-cms-rmpkg

This new tool follows the same approach as #79, where the existing script (`cms-addpkg`) behaves differently depending on the command name. It required some refactoring here, but I think the end result is reasonably concise.
I also made sure the script refers to `$CMSSW_BASE/src/.git` consistently - some commands just used `.git`, which could inconsistencies.

add cms-rmpkg tool

---

git-cms-checkdeps

One-line change to use `cms-addpkg` in `cms-checkdeps` to checkout packages when the `-a` option is enabled. `cms-addpkg` is run in quiet mode since `cms-checkdeps` has its own format for printing the list of packages that will be checked out.
This is desirable after #80 to keep the `sparse-checkout` file in a consistent state, e.g. in a corner case where the user adds a subsystem, removes a package from that subsystem, and then edits another package on which the removed package depends.

use cms-addpkg in cms-checkdeps

---

git-cms-init

- /cvmfs/cms-ib.cern.ch/git/cms-sw/cmssw.git is updated as soon as something is committed in to cmssw repository (plus with cvmfs sync delays b/w CVMFS Stratum 0 to Stratum1's)
- /cvmfs/cms.cern.ch/cmssw.git.daily is updated once a day

use cmssw.git reference from cvmfs if available

---

docs/man/git-cms-checkout-topic.1.in
docs/man/git-cms-merge-topic.1.in
git-cms-merge-topic

As discussed with @smuzaffar in #80, this option will allow further simplification of the patch release build commands:
```
scram p $BASE_REL
cd $BASE_REL/src/
cmsenv
git cms-checkout-topic -A $PATCH_REL
git cms-addpkg -y FWCore/Version
```

add -A option for checkdeps in merge-topic & checkout-topic

---

git-cms-remote

Description:
Adds a remote repository called USER pointing to https://github.com/USER/cmssw.git .
By default only fethcing from this remote is enabled, using the HTTPS protocol.
The default behaviour is to immediately fetch the new remote repository; this can be
disabled with the '--no-fetch' option.
Pushing can be enabled with the '-w' or '--enable-push' option; the default is
to use the SSH protocol.
If '--ssh' is given, the SSH protocol will be used for all URLs.
If '--https' is given, the HTTPS protocol will be used for all URLS.

Add a `git cms-remote` command.

---

Makefile
docs/man/git-cms-checkout-topic.1.in
docs/man/git-cms-merge-topic.1.in
docs/man/git-cms-rebase-topic.1.in
docs/man/man1/git-cms-addpkg.1
docs/man/man1/git-cms-checkout-topic.1
docs/man/man1/git-cms-merge-topic.1
docs/man/man1/git-cms-rebase-topic.1
git-cms-merge-topic
git-cms-rebase-topic

* add a tool `cms-rebase-topic` that is an extension of `cms-checkout-topic` that calls rebase after checking out the branch
* extended rebase syntax (`--onto`) can be activated using the `old-base` option (in case of backports, diverging branches, etc.); the specified old base is also used for the `merge-base` calculation (in any of the related tools; sometimes it's nice to checkout a branch in an old release without getting every package in CMSSW)
* `cms-rebase-topic` and `cms-merge-topic` create a backup branch (named `..._backup`) by default before rebasing or merging, to standardize recovery instructions for users
* actually ran `make` to update the man pages from source (which hadn't been done in a while)

Add cms-rebase-topic and automatic backup branches

---

git-cms-init
git-cms-sparse-checkout

`git cms-init` will now add to the local area `.clang-tidy` (and `.clang-format` when it will be included in the release)

Add support for .clang-tidy and .clang-format

---

git-cms-merge-topic

Requested by @makortel. Tested w/ `CMSSW_10_0_X_2017-11-14-2300` and `git cms-checkout-topic 20879`, in this case, it prints:
```
Warning: pull/20879 is behind from-CMSSW_10_0_X_2017-11-14-2300. You may not be able to compile or run.
```
If instead using `CMSSW_10_0_X_2017-11-14-1100`, no message is printed (as expected).
The message is printed *after* checkdeps, so the user doesn't miss the message in case checkdeps has a long list.

check if topic branch is behind release when using checkout-topic

---

git-cms-merge-topic

Currently, trying to reuse any of the `cms-...-topic` commands with the same remote branch produces error messages like `fatal: A branch named 'foo_backup' already exists.` or `fatal: A branch named 'foo' already exists.`.
The easiest way to fix this is just to overwrite the branch and the backup branch by default (assuming that if the user wants to keep any of these branches, they can rename them, or change the name of the backup branch).
Also noticed that `cms-checkout-topic` was making a backup branch for no reason (it's not supposed to - the relevant arguments aren't shown in the usage), so disabled that.

Allow reuse of topic commands

---

git-cms-init
git-cms-merge-topic
git-cms-remote

`git cms-init --upstream-only` should set up only the `official-cmssw` repository.
Running `git cms-init` again in the same area will add the `my-cmssw` repository.
`git-cms-merge-topic` and `git-cms-remote` will set up only the `official-cmssw` repository (via `git cms-init --upstream-only`).
`git-cms-addpkg`, `git-cms-checkout-topic` and `git-cms-rebase-topic` still set up also the `my-cmssw` repository.

Add an option to setup only the upstream repository

---

git-cms-merge-topic

Tighten the logic to distinguish a branch from a pull request: assume the branch argument to be a pull request only if the full argument is a decimal number, not if oit only begins with a number.

Allow branches that begin with a number

---

Makefile
docs/man/git-cms-rmpkg.1.in
git-cms-addpkg
git-cms-rmpkg

`cms-rmpkg` was originally introduced in #80, but then removed in #83. The problems were:
> * rmpkg can be used to delete a package which was part of a cms-merge-topic. In this case things can fail.
> * when we delete a package (after it has been built once) then it leaves the newly generated files e.g. package/python/*.pyc files in the area. This can also cause problems.
> * SCRAM/build rules also needs update to support rmpkg as it still create lib/$SCRAM_ARCH/.poisonededmplugincache file for the deleted plugins.
This PR addresses the first two concerns by:
* making a list of packages modified after the tag corresponding to `$CMSSW_VERSION` and stopping if any requested packages are on it
* making a list of packages containing untracked files (e.g. `.pyc`) and stopping if any requested …

The return of cms-rmpkg

---

git-cms-init

* Disabling pushing to the official-cmssw remote repository by default; use the new `-w` / `--enable-push` option to avoid this.
* Set up the sparse checkout before switching branch; this leaves the repository in a working state even if the branch is not found.
* If `git-cms-init` is rerun, update the official-cmssw remote.

Minor updates to git-cms-init

---

git-cms-checkdeps

This (along with the change in cmssw-config) should allow to poison cmssw data files. Currently if we delete a data file from a src/package/data area then in cmssw dev area (e.g. for PR tests) then removed data files is picked up from release/src directory.

poison cmssw data files so that removed files are not picked up from release src directory

---

git-cms-init

Set up additional repositories before checking out the release branch.
This allows setting up a release area for releases that are built from different repositories than https://github.com/cms-sw/cmssw/ .

Support additional repositories

---

Makefile
docs/man/git-cms-init.1.in
git-cms-init
git-cms-merge-topic
git-cms-remote

I have noticed that fetching cmssw from GitHub over https is hanging with increasing frequency.
Rather than remember to use the `--ssh` flag every time, I have updated all the relevant commands to take the default access protocol from the user's global `.gitconfig`, if available. (If unavailable, the old default is used.)
I have specified the protocol selection should go in a new "cms" section of the `.gitconfig`, to avoid conflicts with any other settings.
I also noticed there was no man page for `git-cms-init`, so I added one, with a note about the `.gitconfig` protocol setting.

Get default protocol from git config

---

docs/man/git-cms-rebase-topic.1.in
git-cms-merge-topic

It was brought to my attention a while ago that `git-cms-rebase-topic` behaves unlike its sibling commands. If `git-cms-merge-topic` is used twice with branches A and B, the result is base+A+B. If `git-cms-rebase-topic` is used twice, it creates two separate rebased branches A' = base+A and B' = base+B. This is not obvious or intuitive for most naive use of the command.
Therefore, I have updated the command to use the current branch as the default new base for the rebase. This means that using it twice will result in base+A+B (A rebased onto base, B rebased onto base+A).
The old behavior, if desired, can be restored with the argument `--new-base $CMSSW_VERSION`. (I suspect most people were not relying on this old behavior, so changing the default should be fine.)

use current branch as default new_base for rebase

---

git-cms-sparse-checkout

We have noticed  ( https://github.com/cms-sw/cmssw/pull/28881  https://github.com/cms-sw/cmssw/pull/28847 ) that git-cms-sparse-checkout does not checkout packages where we only have renamed files. Problem is that `git diff --name-only`  does not show files which were renamed, passing `--no-renames` option should fix this issue
FYI, @silviodonato , @kpedro88 , @makortel , @fabiocos
[a]
```
diff -u <(git diff CMSSW_11_1_X_2020-02-04-2300..CMSSW_11_1_X_2020-02-05-2300 --name-only) <(git diff CMSSW_11_1_X_2020-02-04-2300..CMSSW_11_1_X_2020-02-05-2300 --name-only --no-renames)
--- /dev/fd/63  2020-02-08 14:12:52.960402077 +0100
+++ /dev/fd/62  2020-02-08 14:12:52.960402077 +0100
@@ -1,3 +1,5 @@
+Configuration/Eras/python/Modifier_dd4hep_cff.py …
```

use no-renames with git diff to get package names with renamed files

---

git-cms-init

Use the standard git configuration "http.proxy" instead of "https.proxy".

Fix the proxy configuration used by git cms-init 

---

git-cms-init

New token only allows to read user info `https://api.github.com/users/<username>`
Resolves https://github.com/cms-sw/cms-git-tools/issues/64

Use cmsbot public readonly token.

---

git-cms-addpkg

The reference repository is not used by `git-cms-addpkg`, so there is no need to update it here.

Do not update the local git cache

---

docs/man/man1/git-cms-checkout-topic.1
docs/man/man1/git-cms-merge-topic.1
git-cms-merge-topic

I kept the `-A|--all-deps` option in the git-cms-merge-topic tool so that it does not break any existing script which is explicitly using it

run checkdeps with -A opt for merge/checkout topic commands

---

git-cms-checkdeps

bug fix: ignore only those packs which exactly match the change set

---

git-cms-cherry-pick-pr
git-cms-fetch-pr
git-cms-show-pr

Update the usage and description of `git cms-cherry-pick-pr`.
Do not show tags and branches in `git cms-show-pr`.

Minor updates

---

git-cms-checkdeps

FYI @iarspider, this should avoid including empty dependency

Bug fix: only keep valid dependencies

---

docs/man/man1/git-cms-rebase-topic.1
docs/man/man1/git-cms-squash-topic.1
git-cms-merge-topic
git-cms-squash-topic

As requested in https://github.com/cms-sw/cms-bot/issues/2080.
This tool is implemented as another `git-cms-merge-topic` variant, primarily to take advantage of the existing backup and old-base options.
It can squash a remote branch (by performing `git-cms-checkout-topic` first) or the current branch in a local working area (using the `--current` flag and not specifying the positional argument for the remote branch name).
By default, it populates the commit message of the squashed commit with all the messages of the original commits, but a custom message can be provided with the `--message` option.
Also did some cleanup in the code and added enforcement of unsupported options (previously, unsupported options weren't shown in the help message but could still be provided, potentially …

Introduce cms-squash-topic

---

git-cms-merge-topic

Addresses issue reported at https://github.com/cms-sw/cms-git-tools/pull/125#issuecomment-1912020011 / https://github.com/cms-sw/cmssw/pull/43592#issuecomment-1911840635. Proof that it works as expected now: https://github.com/kpedro88/cmssw/commit/aac6c7dd3157573fe88ae2d18d871078fef39f66

fix newline in git log format

---

share/etc/profile.d/S99cms-git-tools-completion.sh

The completion is available for both `git-cms-addpkg` and `git cms-addpkg`.

Add bash completion for `git cms-addpkg`

---

git-cms-cvs-history
git-cms-import-tagset
git-cms-showtags

Wrap importing commands in try-catch to have Py3 compatibility
